### PR TITLE
Transfer unused props onto returned component

### PR DESCRIPTION
**Pull request by misund**
I'm spesifically after being able to style the wrapper with the standard style prop.

This approach will pass on any unused props to the wrapping div. The technique is explained in more detail [here](http://reactjs.cn/react/docs/transferring-props.html#rest-and-spread-properties-...).

### CODE REVIEW

**Comment by conorhastings** [comment]
@misund looks good, can you just add something to the README mentioning this! Thanks!

**Comment by misund** [comment]
Will this do?

**Comment by conorhastings** [comment]
looks great, thanks

**Comment by conorhastings** [comment]
@misund published `0.1.0` thanks again!

**Pull request merged**
